### ISSUE TITLE
create hateful language filter on petition signature

### ISSUE THREAD

**Issue by JasonBoyett** [ahmad1702/upload-thing-dark-mode-free#6]
Several people have used the n-word as part of their petition signatures. maybe there should be a filter that makes sure signatures don't have that in them before accepting/displaying them. I'd be happy to make a pr for this if you want me to take care of it.

**Comment by ahmadaccino** [comment]
Yes, thanks for bringing this up. Thanks for the pr, I'll have an all around profanity filter update sometime today. Unfortunately people like to use and abuse.
